on:
  pull_request: ~
  push: ~

name: segfault

permissions:
  contents: read

jobs:
  linux:
    name: Reproduce segfault
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-source --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests
        run: XDEBUG_MODE=coverage ./vendor/bin/codecept run --coverage